version: '3'

services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
    ports:
      - '5432:5432'
    volumes: 
      - ./pgdata:/var/lib/postgresql/data